#!/bin/bash

#结果保存的文件
RESULT=check_result
RESULTx=check_resultx
#连接产生的记录文件
tempfile=mentemp
#connect time
CONDELAY=7
number=
#sudo mentohust -k >/dev/null 2>&1
>$tempfile
for number in `cat $1`
do
#	number=$stunum1$stunum2$stunum3$stunum4
	echo $number
	echo ================$number================== >>$tempfile
	#check 
	echo m1
	sudo mentohust -u$number -p$number -l1 >> $tempfile &
	echo s1
	sleep $CONDELAY
	sudo mentohust -k >/dev/null
	echo s2
	sleep 9
	echo m2
	sudo mentohust -u$number -p$number -b0 -l1 >> $tempfile &
	echo s3
	sleep $CONDELAY
	sudo mentohust -k >/dev/null 
	#cat /tmp/mentohust.log >> $tempfile
	info=`grep "提示" $tempfile | tail -1`
	echo $info | grep "在线用户数量上限" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	fi
	echo $info | grep "不允许抢占" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	fi
	echo $info | grep "接入方式" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULTx
	#sudo mentohust -k
        fi
	echo $info | grep "余额已不足" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	#sudo mentohust -k
        fi
	echo $info | grep "您当前使用的服务" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULTx
	#sudo mentohust -k
        fi
done
exit 0
